### ISSUE TITLE
Oscillator doesn't show in VCV rack!

### ISSUE THREAD

**Issue by jaffasplaffa** [lindenbergresearch/LRTRack#30]
Hello!

I just tried compiling one of the branches, 5.3 and I see all of the modules in Rack, except the oscillator. I also tried the release version for Rack 5 and oscillator doesn't work here either.

Is the oscillator still in development or for some other reason not working yet?

SUPER awesome filters btw. Alma is exceptional. Thanks for sharing :) 

Thanks, Jakob

**Comment by zezic** [comment]
Doubling this. At the moment oscillator partially working for me, but UI is kinda broken. I'm at VCV Rack 0.6 (unstable). Also, thanks for nice filters and utils!

**Comment by lindenbergresearch** [comment]
At first thank's, you are welcome :) 
In version 0.5.x there was no active oscillator released, the code has been excluded because it is still under construction, also on the master. The master branch means ALWAYS the current state of development, it may be buggy or broken somehow. I'll tag released, they are stable... The next release will be for Rack 0.6.x (when it comes out) I hope I can get the VCO done until this... any questions left? :)

**Comment by zezic** [comment]
Umm, I don't have any other questions :) Thank you.

**Comment by jaffasplaffa** [comment]
Thank you for the answers. Keep up the good work ;)
