### ISSUE TITLE
Alam seems to break veeseevee 

### ISSUE THREAD

**Issue by modman2019** [lindenbergresearch/LRTRack#43]
The audio click pops and goes silent using this module for some reason in veesseerack. I removed it and the project works

**Comment by lindenbergresearch** [comment]
I fixed some memory bugs... just retry with the current 0.6.5, hope it works now :)

**Comment by Sir-Fancy** [comment]
I'm assuming this is the same issue that I'm having. I'm using the normal VCV Rack standalone, and if I open a project with Alma in it, I often have to reload it 10+ times before the module cooperates. Otherwise, the project loads in with the output spitting out NaN when viewed with a debugger. I tried with 0.6.5 and didn't work. I've had this issue since I started using this module months ago but now it seems to be getting worse.
Windows 10 - VCV Rack 0.6.2c

**Comment by lindenbergresearch** [comment]
Hi, what about that issue? Still any problems with Alma?

**Comment by modman2019** [comment]
Hello

 

Yes for some reason your plugins give me trouble but I want to use them.  Im using the newest version of FL studio and it was happening in previous version. But it seems to started after a more recent update of Veeseevee.  All of your plugins are doing this
